# Data Import

In [1]:
import collections
import math
import pandas
import os

# This query represents dataset "demo_and_medical_history" for domain "person" and was generated for All of Us Controlled Tier Dataset v6
dataset_99672230_person_sql = """
    SELECT
        person.person_id,
        p_gender_concept.concept_name as gender,
        person.birth_datetime as date_of_birth,
        p_race_concept.concept_name as race,
        p_ethnicity_concept.concept_name as ethnicity,
    FROM
        `""" + os.environ["WORKSPACE_CDR"] + """.person` person 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_gender_concept 
            ON person.gender_concept_id = p_gender_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_race_concept 
            ON person.race_concept_id = p_race_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_ethnicity_concept 
            ON person.ethnicity_concept_id = p_ethnicity_concept.concept_id  
    WHERE
        person.PERSON_ID IN (SELECT
            distinct person_id  
        FROM
            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
        WHERE
            cb_search_person.person_id IN (SELECT
                person_id 
            FROM
                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` p 
            WHERE
                age_at_consent BETWEEN 18 AND 39 ) )"""

dataset_99672230_person_df = pandas.read_gbq(
    dataset_99672230_person_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook")



# This query represents dataset "demo_and_medical_history" for domain "survey" and was generated for All of Us Controlled Tier Dataset v6
dataset_99672230_survey_sql = """
    SELECT
        answer.person_id,
        answer.survey_datetime,
        answer.question_concept_id,
        answer.question,
        answer.answer_concept_id,
        answer.answer  
    FROM
        `""" + os.environ["WORKSPACE_CDR"] + """.ds_survey` answer   
    WHERE
        (
            question_concept_id IN (1384388, 1384390, 1384394, 1384398, 1384399, 1384409, 1384410, 1384416, 1384420, 1384423, 1384430, 1384433, 1384437, 1384442, 1384456, 1384460, 1384462, 1384463, 1384465, 1384468, 1384470, 1384474, 1384476, 1384478, 1384479, 1384487, 1384489, 1384490, 1384493, 1384495, 1384501, 1384505, 1384507, 1384509, 1384511, 1384517, 1384518, 1384522, 1384526, 1384528, 1384532, 1384538, 1384540, 1384542, 1384543, 1384553, 1384554, 1384556, 1384560, 1384566, 1384570, 1384573, 1384576, 1384589, 1384592, 1384593, 1384605, 1384611, 1384612, 1384617, 1384621, 1384624, 1384625, 1384635, 1384636, 1384637, 1384641, 1384647, 1384649, 1384651, 1384661, 1384662, 1384663, 1384664, 1384667, 1384668, 1384671, 1384672, 43528757, 43528758, 43528759, 43528760, 43528770, 43528783, 43528786, 43528787, 43528790, 43528793, 43528800, 43528802, 43528805, 43528806, 43528807, 43528808, 43528809, 43528810, 43528814, 43528815, 43528820, 43528822, 43528823, 43528824, 43528825, 43528826,
 43528828, 43528829, 43528830, 43528834, 43528836, 43528839, 43528841, 43528842, 43528843, 43528844, 43528846, 43528850, 43528851, 43528854, 43528855, 43528856, 43528860, 43528863, 43528866, 43528867, 43528868, 43528869, 43528870, 43528871, 43528872, 43528873, 43528875, 43528877, 43528878, 43528879, 43528880, 43528882, 43528883, 43530286, 43530299, 43530302, 43530303, 43530306, 43530308, 43530309, 43530310, 43530316, 43530318, 43530320, 43530321, 43530322, 43530323, 43530324, 43530325, 43530329, 43530330, 43530335, 43530337, 43530338, 43530339, 43530340, 43530341, 43530343, 43530344, 43530345, 43530349, 43530351, 43530354, 43530356, 43530357, 43530358, 43530359, 43530361, 43530365, 43530366, 43530369, 43530370, 43530371, 43530375, 43530378, 43530381, 43530382, 43530383, 43530384, 43530385, 43530386, 43530387, 43530388, 43530390, 43530392, 43530393, 43530394, 43530395, 43530397, 43530398, 43530414, 43530444, 43530457, 43530461, 43530464, 43530467, 43530468, 43530473, 43530475, 43530477,
 43530478, 43530479, 43530480, 43530481, 43530482, 43530486, 43530487, 43530492, 43530494, 43530495, 43530496, 43530497, 43530498, 43530500, 43530501, 43530502, 43530507, 43530509, 43530512, 43530514, 43530515, 43530516, 43530517, 43530519, 43530523, 43530524, 43530527, 43530528, 43530529, 43530533, 43530537, 43530539, 43530540, 43530541, 43530542, 43530543, 43530544, 43530545, 43530546, 43530548, 43530550, 43530551, 43530552, 43530553, 43530555, 43530556) 
            OR question_concept_id IN (SELECT
                DISTINCT concept_id                         
            FROM
                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c                         
            JOIN
                (SELECT
                    CAST(cr.id as string) AS id                               
                FROM
                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr                               
                WHERE
                    concept_id IN (1585710)                               
                    AND domain_id = 'SURVEY') a 
                    ON (c.path like CONCAT('%', a.id, '.%'))                         
            WHERE
                domain_id = 'SURVEY'                         
                AND type = 'PPI'                         
                AND subtype = 'QUESTION')
        )  
        AND (
            answer.PERSON_ID IN (SELECT
                distinct person_id  
            FROM
                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
            WHERE
                cb_search_person.person_id IN (SELECT
                    person_id 
                FROM
                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` p 
                WHERE
                    age_at_consent BETWEEN 18 AND 39 ) )
        )"""

dataset_99672230_survey_df = pandas.read_gbq(
    dataset_99672230_survey_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook")

Downloading:   0%|          | 0/112236 [00:00<?, ?rows/s]

Downloading:   0%|          | 0/3245726 [00:00<?, ?rows/s]

In [2]:
demo_data = dataset_99672230_person_df
survey_data = dataset_99672230_survey_df

# Data Clean: Demo

In [3]:
demo_data.head()

,person_id,gender,date_of_birth,race,ethnicity
0,2318133,I prefer not to answer,1998-06-15 00:00:00+00:00,I prefer not to answer,PMI: Prefer Not To Answer
1,1357328,I prefer not to answer,1984-06-15 00:00:00+00:00,I prefer not to answer,PMI: Prefer Not To Answer
2,1464404,I prefer not to answer,1981-06-15 00:00:00+00:00,I prefer not to answer,PMI: Prefer Not To Answer
3,1840529,I prefer not to answer,1997-06-15 00:00:00+00:00,I prefer not to answer,PMI: Prefer Not To Answer
4,2061175,I prefer not to answer,1997-06-15 00:00:00+00:00,I prefer not to answer,PMI: Prefer Not To Answer

In [4]:
# change date of birth
demo_data['dob'] = pandas.to_datetime(demo_data['date_of_birth']).dt.date
dob_data = demo_data.drop('date_of_birth', axis = 1)
dob_data.head()

,person_id,gender,race,ethnicity,dob
0,2318133,I prefer not to answer,I prefer not to answer,PMI: Prefer Not To Answer,1998-06-15
1,1357328,I prefer not to answer,I prefer not to answer,PMI: Prefer Not To Answer,1984-06-15
2,1464404,I prefer not to answer,I prefer not to answer,PMI: Prefer Not To Answer,1981-06-15
3,1840529,I prefer not to answer,I prefer not to answer,PMI: Prefer Not To Answer,1997-06-15
4,2061175,I prefer not to answer,I prefer not to answer,PMI: Prefer Not To Answer,1997-06-15

In [5]:
# clean variable values
gender_vals = dob_data['gender']
person_gender = gender_vals.replace(['Not man only, not woman only, prefer not to answer, or skipped', 
                                     'Gender Identity: Transgender', 
                                     'I prefer not to answer',
                                     'Gender Identity: Non Binary',
                                     'Gender Identity: Additional Options', 
                                     'PMI: Skip', 
                                     'No matching concept'],
                                    ['Unknown/Missing',
                                     'Other',
                                     'Unknown/Missing',
                                     'Other',
                                     'Other',
                                     'Unknown/Missing',
                                     'Unknown/Missing'])

race_vals = dob_data['race']
person_race = race_vals.replace(['PMI: Skip', 
                                 'I prefer not to answer', 
                                 'None of these',
                                 'None Indicated', 
                                 'Middle Eastern or North African',
                                 'More than one population',
                                 'Native Hawaiian or Other Pacific Islander', 
                                 'Asian',
                                 'Black or African American'],
                                ['Unknown/Missing',
                                 'Unknown/Missing',
                                 'Unknown/Missing',
                                 'Unknown/Missing',
                                 'Middle Eastern',
                                 'More than one',
                                 'Asian',
                                 'Asian',
                                 'Black'])

eth_vals = dob_data['ethnicity']
person_eth = eth_vals.replace(['PMI: Skip', 
                               'PMI: Prefer Not To Answer',
                               'What Race Ethnicity: Race Ethnicity None Of These',
                               'No matching concept', 
                               'Hispanic or Latino',
                               'Not Hispanic or Latino'], 
                              ['Unknown/Missing',
                               'Unknown/Missing',
                               'Unknown/Missing',
                               'Unknown/Missing',
                               'Hispanic/Latino',
                               'Not Hispanic/Latino'])

demo_replaced = dob_data

# add back to data
demo_replaced['gender'] = person_gender
demo_replaced['race'] = person_race
demo_replaced['ethnicity'] = person_eth

demo_replaced.head()

   person_id           gender             race        ethnicity         dob
0    2318133  Unknown/Missing  Unknown/Missing  Unknown/Missing  1998-06-15
1    1357328  Unknown/Missing  Unknown/Missing  Unknown/Missing  1984-06-15
2    1464404  Unknown/Missing  Unknown/Missing  Unknown/Missing  1981-06-15
3    1840529  Unknown/Missing  Unknown/Missing  Unknown/Missing  1997-06-15
4    2061175  Unknown/Missing  Unknown/Missing  Unknown/Missing  1997-06-15

# Data Clean: Survey

In [6]:
survey_data = dataset_99672230_survey_df
survey_data.head()

,person_id,survey_datetime,question_concept_id,question,answer_concept_id,answer
0,7732586,2021-03-23 03:37:22+00:00,1384495,Mental Health: Mental Health Condition,1384558,Mental Health Condition: Eating Disorder
1,8134996,2021-08-28 05:25:42+00:00,1384526,Nervous System: Nervous System Condition,1384585,Nervous System Condition: Chronic Fatigue
2,1607054,2019-05-12 22:09:12+00:00,43530502,Infectious Diseases: How Old Were You Chronic ...,1385575,How Old Were You Chronic Sinus: Adolescent
3,3373382,2021-10-05 19:43:25+00:00,43528759,Hearing Vision: Hearing Vision Conditions,1384598,Hearing Vision Conditions: No Hearing Eye
4,1866564,2018-10-16 12:54:57+00:00,43530539,Other: How Old Were You Acne,1384971,How Old Were You Acne: Adolescent

In [7]:
# change survey date
survey_data['date'] = pandas.to_datetime(survey_data['survey_datetime']).dt.date
survey_data = survey_data.drop('survey_datetime', axis = 1)
survey_data.head()

,person_id,question_concept_id,question,answer_concept_id,answer,date
0,7732586,1384495,Mental Health: Mental Health Condition,1384558,Mental Health Condition: Eating Disorder,2021-03-23
1,8134996,1384526,Nervous System: Nervous System Condition,1384585,Nervous System Condition: Chronic Fatigue,2021-08-28
2,1607054,43530502,Infectious Diseases: How Old Were You Chronic ...,1385575,How Old Were You Chronic Sinus: Adolescent,2019-05-12
3,3373382,43528759,Hearing Vision: Hearing Vision Conditions,1384598,Hearing Vision Conditions: No Hearing Eye,2021-10-05
4,1866564,43530539,Other: How Old Were You Acne,1384971,How Old Were You Acne: Adolescent,2018-10-16

In [10]:
# get questions for overall health
for question in survey_data['question'].unique():
    if question.startswith('Overall Health') == True:
        print(question)

Overall Health: Health Material Assistance
Overall Health: General Physical Health
Overall Health: Difficult Understand Info
Overall Health: Medical Form Confidence
Overall Health: Hysterectomy History
Overall Health: Average Fatigue 7 Days
Overall Health: General Health
Overall Health: Social Satisfaction
Overall Health: Menstrual Stopped
Overall Health: Everyday Activities
Overall Health: General Mental Health
Overall Health: Ovary Removal History
Overall Health: Outside Travel 6 Month
Overall Health: General Quality
Overall Health: Emotional Problem 7 Days
Overall Health: Organ Transplant
Overall Health: General Social
Overall Health: Average Pain 7 Days
Overall Health: Hysterectomy History Age
Overall Health Ovary Removal History Age

In [11]:
# get current status and overall variables
curr_data = survey_data[survey_data['question'].str.endswith('Currently')]
ovr_data = survey_data[survey_data['question'].isin(['Overall Health: General Quality',
                                                        'Overall Health: General Physical Health',
                                                        'Overall Health: General Mental Health',
                                                        'Overall Health: General Social',
                                                        'Overall Health: General Health'])]

curr_data = curr_data.reset_index().drop('index', axis = 1)
ovr_data = ovr_data.reset_index().drop('index', axis = 1)

## Data Clean: Survey: Current Status

In [12]:
# fix skipped answers - current status variables
print(len(curr_data['answer'].unique()))
new_vals = []


for row_index in range(curr_data.shape[0]):
    ans_response = curr_data['answer'][row_index]
    # check to see if skipped
    if ans_response == 'PMI: Skip':
        question_response = curr_data['question'][row_index]
        split_vals = question_response.split(":")
        question = split_vals[1].strip()
        ans_response = question + ': No'
    new_vals.append(ans_response)
    
    
curr_data['new_vals'] = new_vals
print(len(curr_data['new_vals'].unique()))

curr_data.head()

161
162

,person_id,question_concept_id,question,answer_concept_id,answer,date,new_vals
0,2960015,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2020-12-10,Near Sightedness Currently: Yes
1,7303565,1384617,Skeletal Muscular: Osteoarthritis Currently,1385200,Osteoarthritis Currently: No,2021-03-29,Osteoarthritis Currently: No
2,3407732,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2019-02-20,Near Sightedness Currently: Yes
3,2058419,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2019-01-24,Near Sightedness Currently: Yes
4,1191962,43530394,Skeletal Muscular: Fractured Broken Bone Curre...,43530047,Fractured Broken Bone Currently: Yes,2020-11-25,Fractured Broken Bone Currently: Yes

In [13]:
sorted(curr_data['new_vals'].unique())

['ADHD Currently: No',
 'ADHD Currently: Yes',
 'Acid Reflux Currently: No',
 'Acid Reflux Currently: Yes',
 'Acne Currently: No',
 'Acne Currently: Yes',
 'Alcohol Disorder Currently: No',
 'Alcohol Or Drug Currently: No',
 'Alcohol Or Drug Currently: Yes',
 'Allergies Currently: No',
 'Allergies Currently: Yes',
 'Anemia Currently: No',
 'Anemia Currently: Yes',
 'Anxiety Currently: No',
 'Anxiety Currently: Yes',
 'Asthma Currently: No',
 'Asthma Currently: Yes',
 'Astigmatism Currently: No',
 'Astigmatism Currently: Yes',
 'Atrial Fibrillation Currently: No',
 'Atrial Fibrillation Currently: Yes',
 'Bipolar Currently: No',
 'Bipolar Currently: Yes',
 'Breast Cancer Currently: No',
 'Breast Cancer Currently: Yes',
 'Carpal Tunnel Currently: No',
 'Carpal Tunnel Currently: Yes',
 'Cataracts Currently: No',
 'Cataracts Currently: Yes',
 'Chickenpox Currently: No',
 'Chickenpox Currently: Yes',
 'Chronic Fatigue Currently: No',
 'Chronic Fatigue Currently: Yes',
 'Chronic Sinus Currently: No',
 'Chronic Sinus Currently: Yes',
 'Colon Polyps Currently: No',
 'Colon Polyps Currently: Yes',
 'Concussion Currently: No',
 'Concussion Currently: Yes',
 'Coronary Artery Currently: No',
 'Coronary Artery Currently: Yes',
 'Depression Currently: No',
 'Depression Currently: Yes',
 'Diverticulosis Currently: No',
 'Diverticulosis Currently: Yes',
 'Dry Eyes Currently: No',
 'Dry Eyes Currently: Yes',
 'Eating Disorder Currently: No',
 'Eating Disorder Currently: Yes',
 'Endometriosis Currently: No',
 'Endometriosis Currently: Yes',
 'Enlarged Prostate Currently: No',
 'Enlarged Prostate Currently: Yes',
 'Far Sightedness Currently: No',
 'Far Sightedness Currently: Yes',
 'Fibroids Currently: No',
 'Fibroids Currently: Yes',
 'Fibromyalgia Currently: No',
 'Fibromyalgia Currently: Yes',
 'Fractured Broken Bone Currently: No',
 'Fractured Broken Bone Currently: Yes',
 'Gall Stones Currently: No',
 'Gall Stones Currently: Yes',
 'Glaucoma Currently: No',
 'Glaucoma Currently: Yes',
 'Gout Currently: No',
 'Gout Currently: Yes',
 'Hearing Loss Currently: No',
 'Hearing Loss Currently: Yes',
 'Heart Valve Disease Currently: No',
 'Heart Valve Disease Currently: Yes',
 'Hemorrhoids Currently: No',
 'Hemorrhoids Currently: Yes',
 'Hernia Currently: No',
 'Hernia Currently: Yes',
 'High Cholesterol Currently: No',
 'High Cholesterol Currently: Yes',
 'Hypertension Currently: No',
 'Hypertension Currently: Yes',
 'Hyperthyroidism Currently: No',
 'Hyperthyroidism Currently: Yes',
 'Hypothyroidism Currently: No',
 'Hypothyroidism Currently: Yes',
 'Insomnia Currently: No',
 'Insomnia Currently: Yes',
 'Irritable Bowel Currently: No',
 'Irritable Bowel Currently: Yes',
 'Kidney Stones Currently: No',
 'Kidney Stones Currently: Yes',
 'Liver Condition Currently: No',
 'Liver Condition Currently: Yes',
 'Memory Loss Currently: No',
 'Memory Loss Currently: Yes',
 'Migraine Currently: No',
 'Migraine Currently: Yes',
 'Near Sightedness Currently: No',
 'Near Sightedness Currently: Yes',
 'Neuropathy Currently: No',
 'Neuropathy Currently: Yes',
 'Obesity Currently: No',
 'Obesity Currently: Yes',
 'Osteoarthritis Currently: No',
 'Osteoarthritis Currently: Yes',
 'Osteoporosis Currently: No',
 'Osteoporosis Currently: Yes',
 'Other Arthritis Currently: No',
 'Other Arthritis Currently: Yes',
 'Other Bone Joint Muscle Condition Currently: No',
 'Other Bone Joint Muscle Condition Currently: Yes',
 'Other Brain Nervous System Currently: No',
 'Other Brain Nervous System Currently: Yes',
 'Other Diagnosis Currently: No',
 'Other Diagnosis Currently: Yes',
 'Other Digestive Condition Currently: No',
 'Other Digestive Conditions Currently: No',
 'Other Digestive Conditions Currently: Yes',
 'Other Hearing Eye Condition Currently: No',
 'Other Hearing Eye Condition Currently: Yes',
 'Other Heart Blood Currently: No',
 'Other Heart Blood Currently: Yes',
 'Other Hormone/ Endocrine Condition Currently: No',
 'Other Hormone/ Endocrine Condition Currently: Yes',
 'Other Infectious Disease Currently: No',
 'Other Infectious Disease Currently: Yes',
 'Other Kidney Condition Currently: No',
 'Other Kidney Condition Currently: Yes',
 'Other Lung Condition Currently: No',
 'Other Lung Condition Currently: Yes',
 'PCOS Currently: No',
 'PCOS Currently: Yes',
 'PTSD Currently: No',
 'PTSD Currently: Yes',
 'Prediabetes Currently: No',
 'Prediabetes Currently: Yes',
 'Restless Leg Currently: No',
 'Restless Leg Currently: Yes',
 'Rheumatoid Arthritis Currently: No',
 'Rheumatoid Arthritis Currently: Yes',
 'STIs Currently: No',
 'STIs Currently: Yes',
 'Shingles Currently: No',
 'Shingles Currently: Yes',
 'Skin Cancer Currently: No',
 'Skin Cancer Currently: Yes',
 'Skin Condition Currently: No',
 'Skin Condition Currently: Yes',
 'Sleep Apnea Currently: No',
 'Sleep Apnea Currently: Yes',
 'Spine Muscle Bone Currently: No',
 'Spine Muscle Bone Currently: Yes',
 'Tinnitus Currently: No',
 'Tinnitus Currently: Yes',
 'Type 2 Diabetes Currently: No',
 'Type 2 Diabetes Currently: Yes',
 'Urinary Tract Currently: No',
 'Urinary Tract Currently: Yes',
 'Vitamin B Deficiency Currently: No',
 'Vitamin B Deficiency Currently: Yes',
 'Vitamin D Deficiency Currently: No',
 'Vitamin D Deficiency Currently: Yes',
 'Yeast Infection Currently: No',
 'Yeast Infection Currently: Yes']

In [14]:
# fix two mismatched question-answer pairs

for row_index in range(curr_data.shape[0]):
    ans_response = curr_data['new_vals'][row_index]
    # check to see if one of the two bad coded questions
    if ans_response == 'Other Digestive Condition Currently: No':
        curr_data['new_vals'][row_index] = 'Other Digestive Conditions Currently: No'
    elif ans_response == 'Alcohol Disorder Currently: No':
        curr_data['new_vals'][row_index] = 'Alcohol Or Drug Currently: No'
        
print(len(curr_data['new_vals'].unique()))
curr_data.head()

160

/tmp/ipykernel_112/2874890583.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  curr_data['new_vals'][row_index] = 'Alcohol Or Drug Currently: No'
/tmp/ipykernel_112/2874890583.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  curr_data['new_vals'][row_index] = 'Other Digestive Conditions Currently: No'

,person_id,question_concept_id,question,answer_concept_id,answer,date,new_vals
0,2960015,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2020-12-10,Near Sightedness Currently: Yes
1,7303565,1384617,Skeletal Muscular: Osteoarthritis Currently,1385200,Osteoarthritis Currently: No,2021-03-29,Osteoarthritis Currently: No
2,3407732,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2019-02-20,Near Sightedness Currently: Yes
3,2058419,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2019-01-24,Near Sightedness Currently: Yes
4,1191962,43530394,Skeletal Muscular: Fractured Broken Bone Curre...,43530047,Fractured Broken Bone Currently: Yes,2020-11-25,Fractured Broken Bone Currently: Yes

In [15]:
curr_data['answer'] = curr_data['new_vals']
curr_data = curr_data.drop('new_vals', axis = 1)
curr_data.head()

,person_id,question_concept_id,question,answer_concept_id,answer,date
0,2960015,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2020-12-10
1,7303565,1384617,Skeletal Muscular: Osteoarthritis Currently,1385200,Osteoarthritis Currently: No,2021-03-29
2,3407732,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2019-02-20
3,2058419,43530343,Hearing Vision: Near Sightedness Currently,43530088,Near Sightedness Currently: Yes,2019-01-24
4,1191962,43530394,Skeletal Muscular: Fractured Broken Bone Curre...,43530047,Fractured Broken Bone Currently: Yes,2020-11-25

In [16]:
# get question and answer values from 'answer'
question_array = []
response_array = []

for row_index in range(0, curr_data.shape[0]):
    ans_response = curr_data['answer'][row_index]
    
    # split values on colon, get question (and remove 'currently') and response values
    split_vals = ans_response.split(":")
    question = split_vals[0][:-10] 
    response = split_vals[1].strip()
    
    # append values
    question_array.append(question)
    response_array.append(response)
    
# add variables to dataframe
curr_data['question'] = question_array
curr_data['response'] = response_array
curr_data = curr_data.drop(['question_concept_id', 'answer_concept_id', 'answer'], axis = 1)
curr_data.head()

   person_id               question        date response
0    2960015       Near Sightedness  2020-12-10      Yes
1    7303565         Osteoarthritis  2021-03-29       No
2    3407732       Near Sightedness  2019-02-20      Yes
3    2058419       Near Sightedness  2019-01-24      Yes
4    1191962  Fractured Broken Bone  2020-11-25      Yes

## Data Clean: Survey: Overall

In [17]:
ovr_data.head()

,person_id,question_concept_id,question,answer_concept_id,answer,date
0,1937810,1585723,Overall Health: General Physical Health,1585724,General Physical Health: Excellent,2018-09-27
1,2743933,1585711,Overall Health: General Health,1585712,General Health: Excellent,2018-11-26
2,3070644,1585711,Overall Health: General Health,1585712,General Health: Excellent,2018-10-04
3,3200088,1585723,Overall Health: General Physical Health,1585724,General Physical Health: Excellent,2021-12-20
4,1760833,1585729,Overall Health: General Mental Health,903626,General Mental Health: Excellent,2020-03-06

In [18]:
sorted(ovr_data['answer'].unique())

['General Health: Excellent',
 'General Health: Fair',
 'General Health: Good',
 'General Health: Poor',
 'General Health: Very Good',
 'General Mental Health: Excellent',
 'General Mental Health: Excllent',
 'General Mental Health: Fair',
 'General Mental Health: Good',
 'General Mental Health: Poor',
 'General Mental Health: Very Good',
 'General Physical Health: Excellent',
 'General Physical Health: Fair',
 'General Physical Health: Good',
 'General Physical Health: Poor',
 'General Physical Health: Very Good',
 'General Quality: Excellent',
 'General Quality: Fair',
 'General Quality: Good',
 'General Quality: Poor',
 'General Quality: Very Good',
 'General Social: Excellent',
 'General Social: Fair',
 'General Social: Good',
 'General Social: Poor',
 'General Social: Very Good',
 'PMI: Skip']

In [19]:
# fix skipped answers - overall variables
print(len(ovr_data['answer'].unique()))
new_vals = []

for row_index in range(ovr_data.shape[0]):
    ans_response = ovr_data['answer'][row_index]
    # check to see if mistyped or skipped
    if ans_response == 'General Mental Health: Excllent':
        ans_response = 'General Mental Health: Excellent'
    elif ans_response == 'PMI: Skip':
        question_response = ovr_data['question'][row_index]
        split_vals = question_response.split(":")
        question = split_vals[1].strip()
        ans_response = question + ': Unknown'
    new_vals.append(ans_response)
    
    
ovr_data['new_vals'] = new_vals
print(len(ovr_data['new_vals'].unique()))

sorted(ovr_data['new_vals'].unique())

27
30

['General Health: Excellent',
 'General Health: Fair',
 'General Health: Good',
 'General Health: Poor',
 'General Health: Unknown',
 'General Health: Very Good',
 'General Mental Health: Excellent',
 'General Mental Health: Fair',
 'General Mental Health: Good',
 'General Mental Health: Poor',
 'General Mental Health: Unknown',
 'General Mental Health: Very Good',
 'General Physical Health: Excellent',
 'General Physical Health: Fair',
 'General Physical Health: Good',
 'General Physical Health: Poor',
 'General Physical Health: Unknown',
 'General Physical Health: Very Good',
 'General Quality: Excellent',
 'General Quality: Fair',
 'General Quality: Good',
 'General Quality: Poor',
 'General Quality: Unknown',
 'General Quality: Very Good',
 'General Social: Excellent',
 'General Social: Fair',
 'General Social: Good',
 'General Social: Poor',
 'General Social: Unknown',
 'General Social: Very Good']

In [20]:
# get question and answer values from 'answer'
question_array = []
response_array = []

for row_index in range(0, ovr_data.shape[0]):
    ans_response = ovr_data['new_vals'][row_index]
    
    # split values on colon, get question (and remove 'currently') and response values
    split_vals = ans_response.split(":")
    question = split_vals[0]
    response = split_vals[1].strip()
    
    # append values
    question_array.append(question)
    response_array.append(response)
    
# add variables to dataframe
ovr_data['question'] = question_array
ovr_data['response'] = response_array
ovr_data = ovr_data.drop(['question_concept_id', 'answer_concept_id', 'answer'], axis = 1)
ovr_data.head()

,person_id,question,date,new_vals,response
0,1937810,General Physical Health,2018-09-27,General Physical Health: Excellent,Excellent
1,2743933,General Health,2018-11-26,General Health: Excellent,Excellent
2,3070644,General Health,2018-10-04,General Health: Excellent,Excellent
3,3200088,General Physical Health,2021-12-20,General Physical Health: Excellent,Excellent
4,1760833,General Mental Health,2020-03-06,General Mental Health: Excellent,Excellent

In [21]:
ovr_data = ovr_data[['person_id', 'question', 'response']]
ovr_data.head()

   person_id                 question   response
0    1937810  General Physical Health  Excellent
1    2743933           General Health  Excellent
2    3070644           General Health  Excellent
3    3200088  General Physical Health  Excellent
4    1760833    General Mental Health  Excellent

# Age Calculation

In [22]:
date_data = curr_data[['person_id', 'date']]
date_data.head()

   person_id        date
0    2960015  2020-12-10
1    7303565  2021-03-29
2    3407732  2019-02-20
3    2058419  2019-01-24
4    1191962  2020-11-25

In [23]:
# remove duplicates
print(date_data.shape[0])
print(date_data.duplicated().sum())

no_dups = date_data.drop_duplicates()
no_dups = no_dups.reset_index().drop('index', axis = 1)

print(no_dups.shape[0])
no_dups.head()

268107
232184
35923

   person_id        date
0    2960015  2020-12-10
1    7303565  2021-03-29
2    3407732  2019-02-20
3    2058419  2019-01-24
4    1191962  2020-11-25

In [24]:
# merge demographics and date by id
merged_data = pandas.merge(demo_replaced, no_dups, on = 'person_id')
print(merged_data.shape)
merged_data.head()

(35923, 6)

,person_id,gender,race,ethnicity,dob,date
0,2272845,Unknown/Missing,Unknown/Missing,Unknown/Missing,2000-06-15,2019-11-20
1,2061175,Unknown/Missing,Unknown/Missing,Unknown/Missing,1997-06-15,2020-08-08
2,2987154,Unknown/Missing,Unknown/Missing,Unknown/Missing,1984-06-15,2020-05-29
3,1877627,Unknown/Missing,Unknown/Missing,Unknown/Missing,1991-06-15,2021-03-27
4,1272732,Other,Unknown/Missing,Unknown/Missing,1993-06-15,2019-04-28

In [25]:
# calculate age
merged_data['date'] = merged_data['date'].apply(pandas.Timestamp)
merged_data['dob'] = merged_data['dob'].apply(pandas.Timestamp)
merged_data['age_days'] = (merged_data['date'] - merged_data['dob']).dt.days.astype(int)
merged_data.head()

,person_id,gender,race,ethnicity,dob,date,age_days
0,2272845,Unknown/Missing,Unknown/Missing,Unknown/Missing,2000-06-15,2019-11-20,7097
1,2061175,Unknown/Missing,Unknown/Missing,Unknown/Missing,1997-06-15,2020-08-08,8455
2,2987154,Unknown/Missing,Unknown/Missing,Unknown/Missing,1984-06-15,2020-05-29,13132
3,1877627,Unknown/Missing,Unknown/Missing,Unknown/Missing,1991-06-15,2021-03-27,10878
4,1272732,Other,Unknown/Missing,Unknown/Missing,1993-06-15,2019-04-28,9448

In [26]:
merged_age = merged_data

age_years = []

for row_index in range(merged_data.shape[0]):
    age_days = merged_data['age_days'][row_index]
    num_years = math.floor(age_days / 365)
    age_years.append(num_years)
    
merged_age['age_years'] = age_years
merged_age.head()

,person_id,gender,race,ethnicity,dob,date,age_days,age_years
0,2272845,Unknown/Missing,Unknown/Missing,Unknown/Missing,2000-06-15,2019-11-20,7097,19
1,2061175,Unknown/Missing,Unknown/Missing,Unknown/Missing,1997-06-15,2020-08-08,8455,23
2,2987154,Unknown/Missing,Unknown/Missing,Unknown/Missing,1984-06-15,2020-05-29,13132,35
3,1877627,Unknown/Missing,Unknown/Missing,Unknown/Missing,1991-06-15,2021-03-27,10878,29
4,1272732,Other,Unknown/Missing,Unknown/Missing,1993-06-15,2019-04-28,9448,25

In [27]:
demo_data = merged_age.drop(['dob', 'date', 'age_days'], axis = 1)
demo_data.head()

   person_id           gender             race        ethnicity  age_years
0    2272845  Unknown/Missing  Unknown/Missing  Unknown/Missing         19
1    2061175  Unknown/Missing  Unknown/Missing  Unknown/Missing         23
2    2987154  Unknown/Missing  Unknown/Missing  Unknown/Missing         35
3    1877627  Unknown/Missing  Unknown/Missing  Unknown/Missing         29
4    1272732            Other  Unknown/Missing  Unknown/Missing         25

# Transpose Survey: Long to Wide

In [28]:
curr_data.head()

   person_id               question        date response
0    2960015       Near Sightedness  2020-12-10      Yes
1    7303565         Osteoarthritis  2021-03-29       No
2    3407732       Near Sightedness  2019-02-20      Yes
3    2058419       Near Sightedness  2019-01-24      Yes
4    1191962  Fractured Broken Bone  2020-11-25      Yes

In [29]:
curr_no_date = curr_data.drop('date', axis = 1)
curr_no_date.head()

   person_id               question response
0    2960015       Near Sightedness      Yes
1    7303565         Osteoarthritis       No
2    3407732       Near Sightedness      Yes
3    2058419       Near Sightedness      Yes
4    1191962  Fractured Broken Bone      Yes

In [30]:
# find duplicate rows
pairs = []

for index in range(0, curr_no_date.shape[0]):
    id_val = curr_no_date['person_id'][index]
    q_val = curr_no_date['question'][index]
    pair = str(id_val) + str(q_val)
    pairs.append(pair)
    
print([item for item, count in collections.Counter(pairs).items() if count > 1])

['2053663Near Sightedness', '2325186Near Sightedness']

In [31]:
curr_no_date.loc[curr_no_date['person_id'] == 1000093]

        person_id                     question response
1683      1000093   Other Digestive Conditions       No
18740     1000093                   Depression      Yes
19175     1000093                         Acne      Yes
27987     1000093                    Allergies       No
47497     1000093  Other Hearing Eye Condition      Yes
73791     1000093               Skin Condition       No
94514     1000093                Urinary Tract       No
155824    1000093             Near Sightedness      Yes
235878    1000093                      Anxiety      Yes

In [32]:
# remove duplicates
curr_no_dup = curr_no_date.drop_duplicates()
curr_no_dup = curr_no_dup.reset_index().drop('index', axis = 1)

# transpose
curr_pivot = curr_no_dup.pivot(index = 'person_id', columns = 'question', values = 'response')
curr_pivot = curr_pivot.reset_index()
curr_pivot = curr_pivot.rename_axis(None, axis = 1)
curr_pivot.head()

,person_id,ADHD,Acid Reflux,Acne,Alcohol Or Drug,Allergies,Anemia,Anxiety,Asthma,Astigmatism,...,Skin Cancer,Skin Condition,Sleep Apnea,Spine Muscle Bone,Tinnitus,Type 2 Diabetes,Urinary Tract,Vitamin B Deficiency,Vitamin D Deficiency,Yeast Infection
0,1000093,NaN,NaN,Yes,NaN,No,NaN,Yes,NaN,NaN,...,NaN,No,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN
1,1000095,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Yes,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
2,1000107,NaN,NaN,No,NaN,No,NaN,Yes,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000112,NaN,NaN,No,NaN,NaN,NaN,Yes,No,NaN,...,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN,NaN
4,1000184,NaN,NaN,No,NaN,No,NaN,NaN,NaN,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
ovr_data.head()

   person_id                 question   response
0    1937810  General Physical Health  Excellent
1    2743933           General Health  Excellent
2    3070644           General Health  Excellent
3    3200088  General Physical Health  Excellent
4    1760833    General Mental Health  Excellent

In [34]:
# find duplicate rows
pairs = []

for index in range(0, ovr_data.shape[0]):
    id_val = ovr_data['person_id'][index]
    q_val = ovr_data['question'][index]
    pair = str(id_val) + str(q_val)
    pairs.append(pair)
    
print([item for item, count in collections.Counter(pairs).items() if count > 1])

[]

In [35]:
# transpose
ovr_pivot = ovr_data.pivot(index = 'person_id', columns = 'question', values = 'response')
ovr_pivot = ovr_pivot.reset_index()
ovr_pivot = ovr_pivot.rename_axis(None, axis = 1)
ovr_pivot.head()

,person_id,General Health,General Mental Health,General Physical Health,General Quality,General Social
0,1000079,Excellent,Excellent,Excellent,Very Good,Excellent
1,1000093,Very Good,Good,Very Good,Excellent,Very Good
2,1000095,Good,Very Good,Good,Good,Good
3,1000107,Good,Good,Good,Good,Good
4,1000112,Very Good,Fair,Very Good,Very Good,Good

# Merge All Data Together

In [36]:
demo_data.head()

   person_id           gender             race        ethnicity  age_years
0    2272845  Unknown/Missing  Unknown/Missing  Unknown/Missing         19
1    2061175  Unknown/Missing  Unknown/Missing  Unknown/Missing         23
2    2987154  Unknown/Missing  Unknown/Missing  Unknown/Missing         35
3    1877627  Unknown/Missing  Unknown/Missing  Unknown/Missing         29
4    1272732            Other  Unknown/Missing  Unknown/Missing         25

In [37]:
curr_pivot.head()

,person_id,ADHD,Acid Reflux,Acne,Alcohol Or Drug,Allergies,Anemia,Anxiety,Asthma,Astigmatism,...,Skin Cancer,Skin Condition,Sleep Apnea,Spine Muscle Bone,Tinnitus,Type 2 Diabetes,Urinary Tract,Vitamin B Deficiency,Vitamin D Deficiency,Yeast Infection
0,1000093,NaN,NaN,Yes,NaN,No,NaN,Yes,NaN,NaN,...,NaN,No,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN
1,1000095,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Yes,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
2,1000107,NaN,NaN,No,NaN,No,NaN,Yes,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000112,NaN,NaN,No,NaN,NaN,NaN,Yes,No,NaN,...,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN,NaN
4,1000184,NaN,NaN,No,NaN,No,NaN,NaN,NaN,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
ovr_pivot.head()

,person_id,General Health,General Mental Health,General Physical Health,General Quality,General Social
0,1000079,Excellent,Excellent,Excellent,Very Good,Excellent
1,1000093,Very Good,Good,Very Good,Excellent,Very Good
2,1000095,Good,Very Good,Good,Good,Good
3,1000107,Good,Good,Good,Good,Good
4,1000112,Very Good,Fair,Very Good,Very Good,Good

In [39]:
# set missing values = no
curr_pivot = curr_pivot.fillna('No')
curr_pivot.head()

,person_id,ADHD,Acid Reflux,Acne,Alcohol Or Drug,Allergies,Anemia,Anxiety,Asthma,Astigmatism,...,Skin Cancer,Skin Condition,Sleep Apnea,Spine Muscle Bone,Tinnitus,Type 2 Diabetes,Urinary Tract,Vitamin B Deficiency,Vitamin D Deficiency,Yeast Infection
0,1000093,No,No,Yes,No,No,No,Yes,No,No,...,No,No,No,No,No,No,No,No,No,No
1,1000095,No,Yes,No,No,No,No,No,No,No,...,No,Yes,No,Yes,No,No,No,No,No,No
2,1000107,No,No,No,No,No,No,Yes,No,Yes,...,No,No,No,No,No,No,No,No,No,No
3,1000112,No,No,No,No,No,No,Yes,No,No,...,No,No,No,No,No,No,No,No,No,No
4,1000184,No,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No

In [40]:
# merge demographics and current status by id
merged_temp = pandas.merge(demo_data, curr_pivot, on = 'person_id')
print(merged_temp.shape)
merged_temp.head()

(35923, 85)

,person_id,gender,race,ethnicity,age_years,ADHD,Acid Reflux,Acne,Alcohol Or Drug,Allergies,...,Skin Cancer,Skin Condition,Sleep Apnea,Spine Muscle Bone,Tinnitus,Type 2 Diabetes,Urinary Tract,Vitamin B Deficiency,Vitamin D Deficiency,Yeast Infection
0,2272845,Unknown/Missing,Unknown/Missing,Unknown/Missing,19,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
1,2061175,Unknown/Missing,Unknown/Missing,Unknown/Missing,23,Yes,No,No,Yes,No,...,No,No,No,No,No,No,No,No,No,No
2,2987154,Unknown/Missing,Unknown/Missing,Unknown/Missing,35,No,No,No,No,Yes,...,No,Yes,Yes,No,No,No,No,No,No,No
3,1877627,Unknown/Missing,Unknown/Missing,Unknown/Missing,29,No,No,No,No,Yes,...,No,No,No,No,No,No,No,No,No,No
4,1272732,Other,Unknown/Missing,Unknown/Missing,25,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No

In [41]:
# merge demographics and current status by id
final_merge = pandas.merge(merged_temp, ovr_pivot, on = 'person_id')
print(final_merge.shape)
final_merge.head()

(35923, 90)

,person_id,gender,race,ethnicity,age_years,ADHD,Acid Reflux,Acne,Alcohol Or Drug,Allergies,...,Type 2 Diabetes,Urinary Tract,Vitamin B Deficiency,Vitamin D Deficiency,Yeast Infection,General Health,General Mental Health,General Physical Health,General Quality,General Social
0,2272845,Unknown/Missing,Unknown/Missing,Unknown/Missing,19,No,No,No,No,No,...,No,No,No,No,No,Very Good,Good,Very Good,Good,Very Good
1,2061175,Unknown/Missing,Unknown/Missing,Unknown/Missing,23,Yes,No,No,Yes,No,...,No,No,No,No,No,Fair,Good,Good,Fair,Good
2,2987154,Unknown/Missing,Unknown/Missing,Unknown/Missing,35,No,No,No,No,Yes,...,No,No,No,No,No,Poor,Good,Poor,Fair,Fair
3,1877627,Unknown/Missing,Unknown/Missing,Unknown/Missing,29,No,No,No,No,Yes,...,No,No,No,No,No,Excellent,Good,Very Good,Very Good,Fair
4,1272732,Other,Unknown/Missing,Unknown/Missing,25,No,No,No,No,No,...,No,No,No,No,No,Fair,Poor,Fair,Fair,Fair

# Data Export

In [43]:
import os
import subprocess
import numpy as np
import pandas as pd

# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = final_merge   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'cleaned_data.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
args = ["gsutil", "cp", f"./{destination_filename}", f"{my_bucket}/data/"]
output = subprocess.run(args, capture_output=True)

# print output from gsutil
output.stderr

b'Copying file://./cleaned_data.csv [Content-Type=text/csv]...\n/ [0 files][    0.0 B/ 11.2 MiB]                                                \r-\r- [0 files][  1.0 MiB/ 11.2 MiB]                                                \r\\\r\\ [0 files][  2.8 MiB/ 11.2 MiB]                                                \r|\r/\r/ [0 files][  4.6 MiB/ 11.2 MiB]                                                \r-\r- [0 files][  6.4 MiB/ 11.2 MiB]                                                \r\\\r\\ [0 files][  8.2 MiB/ 11.2 MiB]                                                \r|\r/\r/ [0 files][ 10.0 MiB/ 11.2 MiB]                                                \r-\r- [1 files][ 11.2 MiB/ 11.2 MiB]                                                \r\nOperation completed over 1 objects/11.2 MiB.                                     \n'